name: Jenkins Timeline Plugin Releases

on: 
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Build
              run: make build
            - name: Get version from tag ref
              id: get_version_from_tag
              run: echo ::set-output name=tag::${GITHUB_REF#ref/*/}
            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.get_version_from_tag.outputs.tag }}
                  release_name: Release ${{ steps.get_version_from_tag.outputs.tag }}
                  draft: false
                  prerelease: false
            - name: Upload assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: target/pipeline-timeline.hpi
                  asset_name: jenkins-timeline-plugin.hpi
                  asset_content_type: application/zip
