name: Website

on: [push]

defaults:
    run:
        working-directory: website

jobs:
    lint_and_test_webapp:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  yarn
                  yarn build
            - name: Publish
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: build/jenkins-timeline-plugin
